package server;

public enum ClientToServerPacketIntention {
	
	RESIDUAL,
	SIGN_IN,
	SIGN_UP,
	BUY,
	CONNECT_TO_RANDOM_LOBBY,
	CONNECT_TO_BATTLE_ROYALE_LOBBY,
	CONNECT_TO_CAPTURE_THE_FLAG_LOBBY,
	CONNECT_TO_ARCADE_LOBBY,
	CONNECT_TO_ZOMBIE_INVASION_LOBBY
}
